spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthfintel_db
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
security:
  jwt:
    secret-key: VfUOJbRXfucFvhNrQEultkzidxWJzSJu+s0Hfk6IS0Q=
    expiration: 86400000 # 1 gün
